### PR TITLE
Bumping up version of HttpClient and adding ability for HttpUtil to cons...

### PR DESCRIPTION
**Pull request by selzaharna**
Bumping up version of HttpClient and adding ability for HttpUtil to consume CredentialsProvider

### CODE REVIEW

**Comment by tea-dragon** [comment]
the use of an optional there is.. interesting. The scale of the call certainly permits the overhead, even if enforcing null handling is more typically a concern for return values / parameters interacted with by user code (as this is a parameter to a private method, it only "helps" maintainers).

I assume something about the structure of the method prohibits the usual overloaded args version from sharing enough code with the base, but I strongly recommend making an overloaded version with the previous signature that delegates to this one with the additional `Optional.absent()` argument. I suppose one reason not to do that would be to emphasize that other methods should eventually be changed, but I don't see any comments or arguments to that effect.

fwiw, this class and its friends / dependencies are on the top of our hit list for spinning into their own module (eg. "basis-http"), and that will significantly decrease the possible concerns about versions changing and so on for any future pull requests.

thanks again for the contribution. My changes are only suggestions, so feel free to merge as far as I am concerned.

**Comment by selzaharna** [comment]
Thanks for the suggestions @tea-dragon. I overloaded execute per your suggestion. I think even perhaps using a builder factory may be in order for when basis-http is refactored into it's own module - especially considering some of the inconsistencies of how the parameters are overloaded (CredentialsProviders is wrapped with an Optional, numRetries requires a negative number to ignore, timeoutms a 0, etc.)

**Comment by tea-dragon** [comment]
much of the point of the overloaded version was to obviate the need for the internal calls to add the additional `Optional.absent()`. I think maybe you forgot to remove some of those afterwards.

**Comment by selzaharna** [comment]
Updated by removing Optionals and passing in null

**Comment by tea-dragon** [comment]
using Optional was fine. my most recent comment was that many of the internal calls do not need to be changed at all... because they can use the overloaded version. ie. They shouldn't need to add `, null` either.

**Comment by selzaharna** [comment]
I totally missed your point. I see it now - reverted use of Optional and correctly overloaded this time (I think!)

**Pull request merged**
